### ISSUE TITLE
ERROR: (localhost:2000) failed to read data: timed out

### ISSUE THREAD

**Issue by Chaivara** [carla-simulator/reinforcement-learning#14]
Hi, I'm using trying out this code in windows. I always get this error : ERROR: (localhost:2000) failed to read data: timed out. This is the error trace.
runfile('C:/Users/cvaram/Documents/CARLA_0.9.5/PythonAPI/run_RL.py', args='--city-name Town01 --corl-2017', wdir='C:/Users/cvaramba/Documents/CARLA_0.9.5/PythonAPI')
Reloaded modules: carla, carla.libcarla, carla.driving_benchmark, carla.driving_benchmark.driving_benchmark, carla.client, carla.sensor, carla.transform, carla.carla_server_pb2, carla.tcp, carla.util, carla.driving_benchmark.metrics, carla.planner, carla.planner.planner, carla.planner.city_track, carla.planner.graph, carla.planner.astar, carla.planner.map, carla.planner.grid, carla.planner.converter, carla.settings, carla.driving_benchmark.results_printer, carla.driving_benchmark.recording, carla.driving_benchmark.experiment_suites, carla.driving_benchmark.experiment_suites.basic_experiment_suite, carla.driving_benchmark.experiment, carla.driving_benchmark.experiment_suites.experiment_suite, carla.driving_benchmark.experiment_suites.corl_2017, agent.runnable_model, agent.asyncrl, agent.asyncrl.run_train_test, agent.asyncrl.policy, agent.asyncrl.policy_output, agent.asyncrl.fc_net, agent.asyncrl.nonlinearity, agent.asyncrl.dqn_head, agent.asyncrl.a3c, agent.asyncrl.weight_init, carla.agent, carla.agent.forward_agent, carla.agent.agent

ERROR: (localhost:2000) failed to read data: timed out
ERROR: (localhost:2000) failed to read data: timed out
ERROR: (localhost:2000) failed to read data: timed out
Traceback (most recent call last):

  File "<ipython-input-20-fe538bd622fb>", line 1, in <module>
    runfile('C:/Users/vara/Documents/CARLA_0.9.5/PythonAPI/run_RL.py', args='--city-name Town01 --corl-2017', wdir='C:/Users/vara/Documents/CARLA_0.9.5/PythonAPI')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/vara/Documents/CARLA_0.9.5/PythonAPI/run_RL.py", line 89, in <module>
    args.host, args.port)

  File "C:\Users\vara\Documents\CARLA_0.9.5\PythonAPI\carla\driving_benchmark\driving_benchmark.py", line 280, in run_driving_benchmark
    client.load_settings(CarlaSettings())

  File "C:\Users\vara\Documents\CARLA_0.9.5\PythonAPI\carla\client.py", line 75, in load_settings
    return self._request_new_episode(carla_settings)

  File "C:\Users\vara\Documents\CARLA_0.9.5\PythonAPI\carla\client.py", line 160, in _request_new_episode
    data = self._world_client.read()

  File "C:\Users\vara\Documents\CARLA_0.9.5\PythonAPI\carla\tcp.py", line 73, in read
    header = self._read_n(4)

  File "C:\Users\vara\Documents\CARLA_0.9.5\PythonAPI\carla\tcp.py", line 89, in _read_n
    data = self._socket.recv(length)

Please any help would be appreciated.

**Comment by varunjammula** [comment]
It’s because the code is based on older python API

**Comment by pirate-lofy** [comment]
hey, did u find any solution?

**Comment by josiahcoad** [comment]
I am having the same issue! @varunjammula I am running 0.8.2 Carla. Same issue when running driving_benchmark_example.py in the PythonClient. Windows 10

**Comment by HappyDay-design** [comment]
The same to me. Is there any way to fix it?
